services:

  neo4j:
    image: neo4j:latest
    
    environment:
      - NEO4J_AUTH=neo4j/darixsamani
    ports:
      - "7474:7474"
      - "7687:7687"
  
  web:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env.dev

    depends_on:
      - neo4j

  
    
volumes:
  data:
  data_logs:
